name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release
        uses: BigWigsMods/packager@v1
        with:
          args: -p 88589

      - name: Package and release for Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g classic -p 88589

      - name: Package and release for BCClassic
        uses: BigWigsMods/packager@v1
        with:
          args: -g bc -p 88589
